
package com.hrr3.vendors.hsp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-17T15:09:46.387-06:00
 * Generated source version: 2.7.5
 * 
 */
public final class HspOpenWebServicesSoap_HspOpenWebServicesSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.hotelSystemsPro.com/", "hspOpenWebServices");

    private HspOpenWebServicesSoap_HspOpenWebServicesSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HspOpenWebServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HspOpenWebServices ss = new HspOpenWebServices(wsdlURL, SERVICE_NAME);
        HspOpenWebServicesSoap port = ss.getHspOpenWebServicesSoap();  
        
        {
        System.out.println("Invoking executeQuery...");
        com.hrr3.vendors.hsp.ExecuteQueryRequest _executeQuery_request = new com.hrr3.vendors.hsp.ExecuteQueryRequest();
        com.hrr3.vendors.hsp.htng.HTNGStatisticsRQ _executeQuery_requestHTNGStatisticsRQ = new com.hrr3.vendors.hsp.htng.HTNGStatisticsRQ();
        com.hrr3.vendors.hsp.opentravel.UniqueIDType _executeQuery_requestHTNGStatisticsRQRequestorID = new com.hrr3.vendors.hsp.opentravel.UniqueIDType();
        com.hrr3.vendors.hsp.opentravel.CompanyNameType _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName = new com.hrr3.vendors.hsp.opentravel.CompanyNameType();
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setValue("Value-732391630");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCompanyShortName("CompanyShortName-1336628560");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setTravelSector("TravelSector1280131244");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCode("Code-1788785459");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCodeContext("CodeContext163152804");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setDivision("Division-1186826261");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setDepartment("Department-935641579");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setCompanyName(_executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName);
        _executeQuery_requestHTNGStatisticsRQRequestorID.setInstance("Instance2098578376");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setIDContext("IDContext-1751695383");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setURL("URL-932579220");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setType("Type377507888");
        _executeQuery_requestHTNGStatisticsRQ.setRequestorID(_executeQuery_requestHTNGStatisticsRQRequestorID);
        com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery _executeQuery_requestHTNGStatisticsRQQueries = new com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery();
        java.util.List<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery.Query> _executeQuery_requestHTNGStatisticsRQQueriesQuery = new java.util.ArrayList<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery.Query>();
        _executeQuery_requestHTNGStatisticsRQQueries.getQuery().addAll(_executeQuery_requestHTNGStatisticsRQQueriesQuery);
        _executeQuery_requestHTNGStatisticsRQ.setQueries(_executeQuery_requestHTNGStatisticsRQQueries);
        com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode _executeQuery_requestHTNGStatisticsRQTransactionStatusCode = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode.CONTINUATION;
        _executeQuery_requestHTNGStatisticsRQ.setTransactionStatusCode(_executeQuery_requestHTNGStatisticsRQTransactionStatusCode);
        _executeQuery_requestHTNGStatisticsRQ.setSequenceNmbr(new java.math.BigInteger("-69150708718735980388773870034299055530"));
        _executeQuery_requestHTNGStatisticsRQ.setCorrelationID("CorrelationID-273418890");
        _executeQuery_requestHTNGStatisticsRQ.setRetransmissionIndicator(Boolean.valueOf(true));
        _executeQuery_requestHTNGStatisticsRQ.setTransactionIdentifier("TransactionIdentifier-1937545389");
        _executeQuery_requestHTNGStatisticsRQ.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-17T15:09:46.406-06:00"));
        _executeQuery_requestHTNGStatisticsRQ.setEchoToken("EchoToken-623572195");
        _executeQuery_requestHTNGStatisticsRQ.setVersion(new java.math.BigDecimal("-5513906115197600684.5379135988900812744"));
        com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget _executeQuery_requestHTNGStatisticsRQTarget = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget.PRODUCTION;
        _executeQuery_requestHTNGStatisticsRQ.setTarget(_executeQuery_requestHTNGStatisticsRQTarget);
        _executeQuery_request.setHTNGStatisticsRQ(_executeQuery_requestHTNGStatisticsRQ);
        com.hrr3.vendors.hsp.ExecuteQueryResponse2 _executeQuery__return = port.executeQuery(_executeQuery_request);
        System.out.println("executeQuery.result=" + _executeQuery__return);


        }
        {
        System.out.println("Invoking requestAccessToken...");
        java.lang.String _requestAccessToken_clientId = "_requestAccessToken_clientId1761391647";
        java.lang.String _requestAccessToken_clientSecret = "_requestAccessToken_clientSecret-645185166";
        com.hrr3.vendors.hsp.AccessTokenResponse _requestAccessToken__return = port.requestAccessToken(_requestAccessToken_clientId, _requestAccessToken_clientSecret);
        System.out.println("requestAccessToken.result=" + _requestAccessToken__return);


        }

        System.exit(0);
    }

}
