package com.hrr3.vendors.hsp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-17T15:09:46.498-06:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.hotelSystemsPro.com/", name = "hspOpenWebServicesSoap")
@XmlSeeAlso({ObjectFactory.class, com.hrr3.vendors.hsp.htng.ObjectFactory.class, com.hrr3.vendors.hsp.opentravel.ObjectFactory.class})
public interface HspOpenWebServicesSoap {

    /**
     * hotel SystemsPro HTNG Open Data eXchange Query Request
     */
    @WebResult(name = "ExecuteQueryResult", targetNamespace = "http://www.hotelSystemsPro.com/")
    @RequestWrapper(localName = "ExecuteQuery", targetNamespace = "http://www.hotelSystemsPro.com/", className = "com.hrr3.vendors.hsp.ExecuteQuery")
    @WebMethod(operationName = "ExecuteQuery", action = "http://www.hotelSystemsPro.com/ExecuteQuery")
    @ResponseWrapper(localName = "ExecuteQueryResponse", targetNamespace = "http://www.hotelSystemsPro.com/", className = "com.hrr3.vendors.hsp.ExecuteQueryResponse")
    public com.hrr3.vendors.hsp.ExecuteQueryResponse2 executeQuery(
        @WebParam(name = "request", targetNamespace = "http://www.hotelSystemsPro.com/")
        com.hrr3.vendors.hsp.ExecuteQueryRequest request
    );

    /**
     * hotel SystemsPro Request for Authorization
     */
    @WebResult(name = "RequestAccessTokenResult", targetNamespace = "http://www.hotelSystemsPro.com/")
    @RequestWrapper(localName = "RequestAccessToken", targetNamespace = "http://www.hotelSystemsPro.com/", className = "com.hrr3.vendors.hsp.RequestAccessToken")
    @WebMethod(operationName = "RequestAccessToken", action = "http://www.hotelSystemsPro.com/RequestAccessToken")
    @ResponseWrapper(localName = "RequestAccessTokenResponse", targetNamespace = "http://www.hotelSystemsPro.com/", className = "com.hrr3.vendors.hsp.RequestAccessTokenResponse")
    public com.hrr3.vendors.hsp.AccessTokenResponse requestAccessToken(
        @WebParam(name = "client_id", targetNamespace = "http://www.hotelSystemsPro.com/")
        java.lang.String clientId,
        @WebParam(name = "client_secret", targetNamespace = "http://www.hotelSystemsPro.com/")
        java.lang.String clientSecret
    );
}
