
package com.hrr3.vendors.hsp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-17T15:09:46.298-06:00
 * Generated source version: 2.7.5
 * 
 */
public final class HspOpenWebServicesSoap_HspOpenWebServicesSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.hotelSystemsPro.com/", "hspOpenWebServices");

    private HspOpenWebServicesSoap_HspOpenWebServicesSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HspOpenWebServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HspOpenWebServices ss = new HspOpenWebServices(wsdlURL, SERVICE_NAME);
        HspOpenWebServicesSoap port = ss.getHspOpenWebServicesSoap12();  
        
        {
        System.out.println("Invoking executeQuery...");
        com.hrr3.vendors.hsp.ExecuteQueryRequest _executeQuery_request = new com.hrr3.vendors.hsp.ExecuteQueryRequest();
        com.hrr3.vendors.hsp.htng.HTNGStatisticsRQ _executeQuery_requestHTNGStatisticsRQ = new com.hrr3.vendors.hsp.htng.HTNGStatisticsRQ();
        com.hrr3.vendors.hsp.opentravel.UniqueIDType _executeQuery_requestHTNGStatisticsRQRequestorID = new com.hrr3.vendors.hsp.opentravel.UniqueIDType();
        com.hrr3.vendors.hsp.opentravel.CompanyNameType _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName = new com.hrr3.vendors.hsp.opentravel.CompanyNameType();
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setValue("Value-1559258863");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCompanyShortName("CompanyShortName1478210713");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setTravelSector("TravelSector1063148278");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCode("Code602616556");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setCodeContext("CodeContext-1310726762");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setDivision("Division1761373854");
        _executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName.setDepartment("Department-547235642");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setCompanyName(_executeQuery_requestHTNGStatisticsRQRequestorIDCompanyName);
        _executeQuery_requestHTNGStatisticsRQRequestorID.setInstance("Instance2117268529");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setIDContext("IDContext-95275286");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setURL("URL620357197");
        _executeQuery_requestHTNGStatisticsRQRequestorID.setType("Type199007896");
        _executeQuery_requestHTNGStatisticsRQ.setRequestorID(_executeQuery_requestHTNGStatisticsRQRequestorID);
        com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery _executeQuery_requestHTNGStatisticsRQQueries = new com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery();
        java.util.List<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery.Query> _executeQuery_requestHTNGStatisticsRQQueriesQuery = new java.util.ArrayList<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRQQuery.Query>();
        _executeQuery_requestHTNGStatisticsRQQueries.getQuery().addAll(_executeQuery_requestHTNGStatisticsRQQueriesQuery);
        _executeQuery_requestHTNGStatisticsRQ.setQueries(_executeQuery_requestHTNGStatisticsRQQueries);
        com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode _executeQuery_requestHTNGStatisticsRQTransactionStatusCode = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode.ROLLBACK;
        _executeQuery_requestHTNGStatisticsRQ.setTransactionStatusCode(_executeQuery_requestHTNGStatisticsRQTransactionStatusCode);
        _executeQuery_requestHTNGStatisticsRQ.setSequenceNmbr(new java.math.BigInteger("-3219189609511364347523910816253561820"));
        _executeQuery_requestHTNGStatisticsRQ.setCorrelationID("CorrelationID-116456916");
        _executeQuery_requestHTNGStatisticsRQ.setRetransmissionIndicator(Boolean.valueOf(true));
        _executeQuery_requestHTNGStatisticsRQ.setTransactionIdentifier("TransactionIdentifier581992801");
        _executeQuery_requestHTNGStatisticsRQ.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-17T15:09:46.368-06:00"));
        _executeQuery_requestHTNGStatisticsRQ.setEchoToken("EchoToken-2122610465");
        _executeQuery_requestHTNGStatisticsRQ.setVersion(new java.math.BigDecimal("70377563838138447.4861965813473030390"));
        com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget _executeQuery_requestHTNGStatisticsRQTarget = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget.PRODUCTION;
        _executeQuery_requestHTNGStatisticsRQ.setTarget(_executeQuery_requestHTNGStatisticsRQTarget);
        _executeQuery_request.setHTNGStatisticsRQ(_executeQuery_requestHTNGStatisticsRQ);
        com.hrr3.vendors.hsp.ExecuteQueryResponse2 _executeQuery__return = port.executeQuery(_executeQuery_request);
        System.out.println("executeQuery.result=" + _executeQuery__return);


        }
        {
        System.out.println("Invoking requestAccessToken...");
        java.lang.String _requestAccessToken_clientId = "_requestAccessToken_clientId-1235648053";
        java.lang.String _requestAccessToken_clientSecret = "_requestAccessToken_clientSecret701081076";
        com.hrr3.vendors.hsp.AccessTokenResponse _requestAccessToken__return = port.requestAccessToken(_requestAccessToken_clientId, _requestAccessToken_clientSecret);
        System.out.println("requestAccessToken.result=" + _requestAccessToken__return);


        }

        System.exit(0);
    }

}
