package com.hrr3.vendors.hsp;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * hotel SystemPro Open Web Services
 *
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-17T15:09:46.523-06:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "hspOpenWebServices", 
                  wsdlLocation = "http://209.162.190.128/hspOpenWebService/hspOpenWebService.asmx?wsdl",
                  targetNamespace = "http://www.hotelSystemsPro.com/") 
public class HspOpenWebServices extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.hotelSystemsPro.com/", "hspOpenWebServices");
    public final static QName HspOpenWebServicesSoap12 = new QName("http://www.hotelSystemsPro.com/", "hspOpenWebServicesSoap12");
    public final static QName HspOpenWebServicesSoap = new QName("http://www.hotelSystemsPro.com/", "hspOpenWebServicesSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://209.162.190.128/hspOpenWebService/hspOpenWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HspOpenWebServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/vlarios/workspace/HRR3/src/com/hrr3/vendors/HSPWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HspOpenWebServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HspOpenWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HspOpenWebServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HspOpenWebServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HspOpenWebServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HspOpenWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HspOpenWebServicesSoap
     */
    @WebEndpoint(name = "hspOpenWebServicesSoap12")
    public HspOpenWebServicesSoap getHspOpenWebServicesSoap12() {
        return super.getPort(HspOpenWebServicesSoap12, HspOpenWebServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HspOpenWebServicesSoap
     */
    @WebEndpoint(name = "hspOpenWebServicesSoap12")
    public HspOpenWebServicesSoap getHspOpenWebServicesSoap12(WebServiceFeature... features) {
        return super.getPort(HspOpenWebServicesSoap12, HspOpenWebServicesSoap.class, features);
    }
    /**
     *
     * @return
     *     returns HspOpenWebServicesSoap
     */
    @WebEndpoint(name = "hspOpenWebServicesSoap")
    public HspOpenWebServicesSoap getHspOpenWebServicesSoap() {
        return super.getPort(HspOpenWebServicesSoap, HspOpenWebServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HspOpenWebServicesSoap
     */
    @WebEndpoint(name = "hspOpenWebServicesSoap")
    public HspOpenWebServicesSoap getHspOpenWebServicesSoap(WebServiceFeature... features) {
        return super.getPort(HspOpenWebServicesSoap, HspOpenWebServicesSoap.class, features);
    }

}
