
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hrr3.vendors.hsp;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-17T15:09:46.417-06:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "hspOpenWebServices",
                      portName = "hspOpenWebServicesSoap12",
                      targetNamespace = "http://www.hotelSystemsPro.com/",
                      wsdlLocation = "file:/C:/Users/vlarios/workspace/HRR3/src/com/hrr3/vendors/HSPWebService.wsdl",
                      endpointInterface = "com.hrr3.vendors.hsp.HspOpenWebServicesSoap")
                      
public class HspOpenWebServicesSoapImpl implements HspOpenWebServicesSoap {

    private static final Logger LOG = Logger.getLogger(HspOpenWebServicesSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hrr3.vendors.hsp.HspOpenWebServicesSoap#executeQuery(com.hrr3.vendors.hsp.ExecuteQueryRequest  request )*
     */
    public com.hrr3.vendors.hsp.ExecuteQueryResponse2 executeQuery(com.hrr3.vendors.hsp.ExecuteQueryRequest request) { 
        LOG.info("Executing operation executeQuery");
        System.out.println(request);
        try {
            com.hrr3.vendors.hsp.ExecuteQueryResponse2 _return = new com.hrr3.vendors.hsp.ExecuteQueryResponse2();
            com.hrr3.vendors.hsp.htng.HTNGStatisticsRS _returnHTNGStatisticsRS = new com.hrr3.vendors.hsp.htng.HTNGStatisticsRS();
            com.hrr3.vendors.hsp.opentravel.UniqueIDType _returnHTNGStatisticsRSRequestorID = new com.hrr3.vendors.hsp.opentravel.UniqueIDType();
            com.hrr3.vendors.hsp.opentravel.CompanyNameType _returnHTNGStatisticsRSRequestorIDCompanyName = new com.hrr3.vendors.hsp.opentravel.CompanyNameType();
            _returnHTNGStatisticsRSRequestorIDCompanyName.setValue("Value1536361383");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setCompanyShortName("CompanyShortName353224049");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setTravelSector("TravelSector1990149261");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setCode("Code1371251482");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setCodeContext("CodeContext853954662");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setDivision("Division52142517");
            _returnHTNGStatisticsRSRequestorIDCompanyName.setDepartment("Department-1054513156");
            _returnHTNGStatisticsRSRequestorID.setCompanyName(_returnHTNGStatisticsRSRequestorIDCompanyName);
            _returnHTNGStatisticsRSRequestorID.setInstance("Instance-1678582453");
            _returnHTNGStatisticsRSRequestorID.setIDContext("IDContext150447442");
            _returnHTNGStatisticsRSRequestorID.setURL("URL-460060864");
            _returnHTNGStatisticsRSRequestorID.setType("Type1498553515");
            _returnHTNGStatisticsRS.setRequestorID(_returnHTNGStatisticsRSRequestorID);
            com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRSQuery _returnHTNGStatisticsRSQueries = new com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRSQuery();
            java.util.List<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRSQuery.Query> _returnHTNGStatisticsRSQueriesQuery = new java.util.ArrayList<com.hrr3.vendors.hsp.htng.ArrayOfHTNGStatisticsRSQuery.Query>();
            _returnHTNGStatisticsRSQueries.getQuery().addAll(_returnHTNGStatisticsRSQueriesQuery);
            _returnHTNGStatisticsRS.setQueries(_returnHTNGStatisticsRSQueries);
            com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode _returnHTNGStatisticsRSTransactionStatusCode = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTransactionStatusCode.CONTINUATION;
            _returnHTNGStatisticsRS.setTransactionStatusCode(_returnHTNGStatisticsRSTransactionStatusCode);
            _returnHTNGStatisticsRS.setSequenceNmbr(new java.math.BigInteger("-55835289640379812784954742769218026107"));
            _returnHTNGStatisticsRS.setCorrelationID("CorrelationID1143876801");
            _returnHTNGStatisticsRS.setRetransmissionIndicator(Boolean.valueOf(true));
            _returnHTNGStatisticsRS.setTransactionIdentifier("TransactionIdentifier-1155943623");
            _returnHTNGStatisticsRS.setTimeStamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-17T15:09:46.438-06:00").toString());
            _returnHTNGStatisticsRS.setEchoToken("EchoToken1841182124");
            _returnHTNGStatisticsRS.setVersion(new java.math.BigDecimal("-3284903040024911399.8238820798149847334"));
            com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget _returnHTNGStatisticsRSTarget = com.hrr3.vendors.hsp.opentravel.HTNGStatisticsRQTarget.PRODUCTION;
            _returnHTNGStatisticsRS.setTarget(_returnHTNGStatisticsRSTarget);
            _return.setHTNGStatisticsRS(_returnHTNGStatisticsRS);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hrr3.vendors.hsp.HspOpenWebServicesSoap#requestAccessToken(java.lang.String  clientId ,)java.lang.String  clientSecret )*
     */
    public com.hrr3.vendors.hsp.AccessTokenResponse requestAccessToken(java.lang.String clientId,java.lang.String clientSecret) { 
        LOG.info("Executing operation requestAccessToken");
        System.out.println(clientId);
        System.out.println(clientSecret);
        try {
            com.hrr3.vendors.hsp.AccessTokenResponse _return = new com.hrr3.vendors.hsp.AccessTokenResponse();
            com.hrr3.vendors.hsp.AccessTokenResponse.HSPAccessTokenResponse _returnHSPAccessTokenResponse = new com.hrr3.vendors.hsp.AccessTokenResponse.HSPAccessTokenResponse();
            com.hrr3.vendors.hsp.HSPAccessTokenResponseType _returnHSPAccessTokenResponseResponseType = com.hrr3.vendors.hsp.HSPAccessTokenResponseType.TOKEN;
            _returnHSPAccessTokenResponse.setResponseType(_returnHSPAccessTokenResponseResponseType);
            _returnHSPAccessTokenResponse.setErrorResponse("ErrorResponse-1992081034");
            _returnHSPAccessTokenResponse.setTokenExpiration(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-17T15:09:46.442-06:00"));
            _returnHSPAccessTokenResponse.setAccessToken("AccessToken211262887");
            _return.setHSPAccessTokenResponse(_returnHSPAccessTokenResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
